version: "3.9"

services:
  api:
    build: .
    container_name: calcservice
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - calc_net

  db:
    image: postgres:16
    container_name: calcservice_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - calc_pgdata:/var/lib/postgresql/data
    networks:
      - calc_net

  pg:
    image: dpage/pgadmin4
    container_name: pg_adm
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@te.st
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - calc_net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: calcservice_rabbitmq
    restart: always
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI
    environment:
      - RABBITMQ_DEFAULT_USER:${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS:${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - calc_net

volumes:
  calc_pgdata:
  rabbitmq_data:
  pgadmin_data:

networks:
  calc_net:
    driver: bridge